import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header/Header";
import { IconLoading } from "../components/icons";
import { useFetch } from "../hooks/useFetch";
import { client } from "../lib/apis";

const Home: NextPage = () => {
  const { data, isLoading } = useFetch({
    api: () => client.getUsers(),
  });

  let content: JSX.Element | null = null;
  if (isLoading) {
    content = (
      <div className="animate-spin w-max">
        <IconLoading />
      </div>
    );
  } else if (!data || !data?.length) {
    content = <div>No users found</div>;
  } else if (data?.length) {
    content = (
      <div>
        {data.map((d) => (
          <div key={d.id}>{d.name}</div>
        ))}
      </div>
    );
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <section>
          <div className="section-container px-[90px] py-[43px]">
            <h1 className="text-2xl leading-9">List user page</h1>
            {content}
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
